# Generated by Django 5.1.4 on 2025-02-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
