# Generated by Django 5.1.4 on 2025-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_privet',
            field=models.BooleanField(default=False),
        ),
    ]
