# Generated by Django 5.1.4 on 2025-02-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_privet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
