# Generated by Django 5.1.4 on 2025-02-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_privet',
        ),
    ]
